7_task_wine:    [pick_up_cup,phone_on_base,pick_and_lift,put_rubbish_in_bin,reach_target,take_lid_off_saucepan,take_umbrella_out_of_umbrella_stand]
7_task_target: [pick_up_cup,phone_on_base,pick_and_lift,put_rubbish_in_bin,stack_wine,take_lid_off_saucepan,take_umbrella_out_of_umbrella_stand]
7_task_phone: [pick_up_cup,stack_wine,pick_and_lift,put_rubbish_in_bin,reach_target,take_lid_off_saucepan,take_umbrella_out_of_umbrella_stand]
7_task_cup: [phone_on_base,stack_wine,pick_and_lift,put_rubbish_in_bin,reach_target,take_lid_off_saucepan,take_umbrella_out_of_umbrella_stand]

tasks: ???
short_names: ??? 
run_name: burn 
log_path: ??? 
rlbench:
    task: ''
    tasks: ${tasks}
    demos: 10
    demo_path: /home/mandi/ARM/data
    episode_length: 10
    cameras: [front]
    camera_resolution: [128, 128]
    scene_bounds: [-0.3, -0.5, 0.6, 0.7, 0.5, 1.6]

replay:
    batch_size: 9
    timesteps: 1
    prioritisation: True
    use_disk: False
    path: '/tmp/arm_sanity/replay'  # Only used when use_disk is True.
    share_across_tasks: False

framework:
    log_freq: 100
    train_envs: 2
    eval_envs: 2
    replay_ratio: 128
    transitions_before_train: 100
    tensorboard_logging: True
    csv_logging: False
    wandb_logging: True
    training_iterations: 5000
    gpu: 0
    logdir: '/home/mandi/ARM/log/'
    seeds: 1
    resume: ${resume}
    resume_path: ${resume_path}
    resume_run: ${resume_run}
    resume_step:  ${resume_step}
    resume_dir: ''


resume: False
resume_path: '/home/mandi/ARM/log/'
resume_run: ''
resume_step: 24300

dev:
    q_thres: 0.75 
    save_freq: 100
contexts:
    with_action: False
    context_size: 32 
    pass_down_context: False 

defaults:
    - method: C2FARM

wandb:
    job_type: 'launch'
    group:    'single'
hydra:
    run:
        dir: ${framework.logdir}/ #${rlbench.task}/${method.name}
