rlbench:
    tasks: [take_lid_off_saucepan,take_umbrella_out_of_umbrella_stand]

    demos: 10
    demo_path: /home/mandi/ARM/data
    episode_length: 10
    cameras: [front]
    camera_resolution: [128, 128]
    scene_bounds: [-0.3, -0.5, 0.6, 0.7, 0.5, 1.6]
    single_env_cfg:
        # below are shared across tasks:
        episode_length: ${rlbench.episode_length}
        dataset_root: ${rlbench.demo_path}
        headless: True 
        state_includes_remaining_time: False

replay:
    batch_size: 128
    timesteps: 1
    prioritisation: True
    use_disk: False
    path: '/home/mandi/ARM/replay'  # Only used when use_disk is True.

framework:
    log_freq: 100
    train_envs: 1
    eval_envs: 1
    replay_ratio: 128
    transitions_before_train: 200
    tensorboard_logging: False
    csv_logging: True
    training_iterations: 40000
    gpu: 0
    logdir: '/home/mandi/ARM/log/'
    seeds: 1

defaults:
    - method: C2FARM

log_path: ??? 
short_names: ???
hydra:
    run:
        dir: ${framework.logdir}/ #${rlbench.task}/${method.name}